/*
 * Create your own language definition here
 * You can safely look at other samples without losing modifications.
 * Modifications are not saved on browser refresh/close though -- copy often!
 */
const rules = {
	tokenPostfix: ".wikitext",
	ignoreCase: true,
	/*
	 * Set defaultToken to invalid to see what you do not tokenize yet
	 * defaultToken: 'invalid',
	 */

	brackets: [
		{ open: "(", close: ")", token: "delimiter.parenthesis" },
		{ open: "{", close: "}", token: "delimiter.curly" },
		{ open: "[", close: "]", token: "delimiter.square" },
		/*
		 * { open: '"', close: '"', token: "delimiter.double-qoute" },
		 * { open: "'", close: "'", token: "delimiter.single-qoute" },
		 */
	],

	// The main tokenizer for our languages
	tokenizer: {
		root: [
			[/<!--/u, "comment.start", "@comment"],
			[/__[A-Za-z]+__/u, {
				cases: {
					"@behaviorSwitches": "keyword",
					"@default": "invalid",
				},
			}],
			[/{{/, { token: "braces.start", next: "@template" }],
			// markup within lines
			{ include: "@linecontent" },
		],

		template: [
			[/(#)(\w+)(:)/u, ["keyword.parserfunction.hash", {
				cases: {
					"@parserFunctions": "keyword.parserfunction.name",
					"@default": "invalid",
				},
			}, "keyword.parserfunction.colon"], "@templateParams"],
			[/(#)(\w+)(\|)/u, ["invalid", "invalid", "invalid"], "@templateParams"],
			[/(#)(\w+)(}})/, ["invalid", "invalid", "braces.end"], "@pop"],
			[/(\w+)(\|)/u, ["template.name", "template.pipe"], "@templateParams"],
			[/(\w+)(\}})/, ["template.name", "braces.end"], "@pop"],
		],

		linecontent: [
			// escapes
			[/&\w+;/u, "string.escape"],

			// various markup
			[/'''/u, "keyword.bold.begin", "@bold"],
			[/''/u, "keyword.italics.begin", "@italics"],
			[/^(\s*)(={6})(.+?)(={6})/u, ["whitespace", "keyword.header-level-6.begin", "strong.header-level-6.name", "keyword.header-level-6.end"]],
			[/^(\s*)(={5})(.+?)(={5})/u, ["whitespace", "keyword.header-level-5.begin", "strong.header-level-5.name", "keyword.header-level-5.end"]],
			[/^(\s*)(={4})(.+?)(={4})/u, ["whitespace", "keyword.header-level-4.begin", "strong.header-level-4.name", "keyword.header-level-4.end"]],
			[/^(\s*)(={3})(.+?)(={3})/u, ["whitespace", "keyword.header-level-3.begin", "strong.header-level-3.name", "keyword.header-level-3.end"]],
			[/^(\s*)(={2})(.+?)(={2})/u, ["whitespace", "keyword.header-level-2.begin", "strong.header-level-2.name", "keyword.header-level-2.end"]],
			[/^(\s*)(=)(.+?)(=)/u, ["whitespace", "keyword.header-level-1.begin", "strong.header-level-1.name", "keyword.header-level-1.end"]],
		],

		italics: [
			[/''/u, "keyword.italics.end", "@pop"],
			{ include: "@linecontent" },
			[/./, "emphasis.italics.content"],
		],

		bold: [
			[/'''/u, "keyword.bold.end", "@pop"],
			{ include: "@linecontent" },
			[/./, "strong.bold.content"],
		],

		templateParams: [
			[/./, "template.content"],
		],

		comment: [
			[/-->/u, "comment.end", "@pop"],
			[/[^-]+/, "comment.content"],
			[/./, "comment.content"],
		],

		whitespace: [
			[/[\t\n\r ]+/u, "white"],
			[/\/\*/u, "comment", "@comment"],
			[/\/\/.*$/u, "comment"],
		],
	},

	parserTags: [
		"<activityfeed>",
		"<archiveorg>",
		"<bambuser>",
		"<bambuser_channel>",
		"<beam>",
		"<bing>",
		"<blip>",
		"<bloglist>",
		"<categorytree>",
		"<ce>",
		"<charinsert>",
		"<chem>",
		"<choose>",
		"<collegehumor>",
		"<comments>",
		"<coordinates>",
		"<dailymotion>",
		"<disclose>",
		"<discussions>",
		"<display_line>",
		"<display_map>",
		"<display_point>",
		"<display_points>",
		"<distance>",
		"<divshare>",
		"<dpl>",
		"<dynamicpagelist>",
		"<embedvideo>",
		"<evlplayer>",
		"<facebook>",
		"<fb:follow>",
		"<fb:like-box>",
		"<fb:like>",
		"<fb:page>",
		"<fb:share-button>",
		"<finddestination>",
		"<forum>",
		"<funnyordie>",
		"<gallery>",
		"<geocode>",
		"<geodistance>",
		"<gfycat>",
		"<helper>",
		"<imagemap>",
		"<imap>",
		"<indicator>",
		"<infobox>",
		"<inputbox>",
		"<jwplayer>",
		"<kickstarter>",
		"<loggedin>",
		"<loggedout>",
		"<mainpage-endcolumn>",
		"<mainpage-leftcolumn-start>",
		"<mainpage-rightcolumn-start>",
		"<maplib>",
		"<mapsdoc>",
		"<math>",
		"<mediacccde>",
		"<metacafe>",
		"<metadesc>",
		"<microsoftstream>",
		"<mixer>",
		"<mp3>",
		"<nico>",
		"<nowiki>",
		"<pageby>",
		"<pagetools>",
		"<poem>",
		"<poll>",
		"<pre>",
		"<randomimage>",
		"<ref>",
		"<references>",
		"<rhtml>",
		"<rss>",
		"<rutube>",
		"<section>",
		"<smashcast>",
		"<soundcloud>",
		"<source>",
		"<spotify>",
		"<spotifyalbum>",
		"<spotifyartist>",
		"<spotifytrack>",
		"<staff>",
		"<syntaxhighlight>",
		"<tabber>",
		"<teachertube>",
		"<ted>",
		"<templatedata>",
		"<timeline>",
		"<tubitv>",
		"<tudou>",
		"<tvpot>",
		"<twitch>",
		"<twitchclip>",
		"<twitchvod>",
		"<twitter>",
		"<verbatim>",
		"<videomaten>",
		"<vimeo>",
		"<vine>",
		"<vote>",
		"<vplayer>",
		"<widget>",
		"<yahoo>",
		"<youku>",
		"<youtube>",
		"<youtubeplaylist>",
		"<youtubevideolist>",
	],
	parserFunctions: [
		"anchorencode",
		"basepagename",
		"basepagenamee",
		"bidi",
		"canonicalurl",
		"canonicalurle",
		"cascadingsources",
		"categorytree",
		"choose",
		"coordinates",
		"count",
		"defaultsort",
		"display_line",
		"display_map",
		"display_point",
		"display_points",
		"displaytitle",
		"distance",
		"dpl",
		"dplchapter",
		"dplmatrix",
		"dplnum",
		"dplreplace",
		"dplvar",
		"ev",
		"evl",
		"evp",
		"evt",
		"evu",
		"explode",
		"expr",
		"filepath",
		"finddestination",
		"formatdate",
		"formatnum",
		"forumlink",
		"fullpagename",
		"fullpagenamee",
		"fullurl",
		"fullurle",
		"gender",
		"geocode",
		"geodistance",
		"google_maps",
		"grammar",
		"if",
		"ifeq",
		"iferror",
		"ifexist",
		"ifexpr",
		"int",
		"invoke",
		"language",
		"lc",
		"lcfirst",
		"leaflet",
		"len",
		"localurl",
		"localurle",
		"lst",
		"lsth",
		"lstx",
		"mapsdoc",
		"namespace",
		"namespacee",
		"namespacenumber",
		"ns",
		"nse",
		"numberingroup",
		"numberofactiveusers",
		"numberofadmins",
		"numberofarticles",
		"numberofedits",
		"numberoffiles",
		"numberofpages",
		"numberofusers",
		"padleft",
		"padright",
		"pageid",
		"pagename",
		"pagenamee",
		"pagesincategory",
		"pagesize",
		"plural",
		"pos",
		"protectionexpiry",
		"protectionlevel",
		"rel2abs",
		"replace",
		"revisionday",
		"revisionday2",
		"revisionid",
		"revisionmonth",
		"revisionmonth1",
		"revisiontimestamp",
		"revisionuser",
		"revisionyear",
		"rootpagename",
		"rootpagenamee",
		"rpos",
		"setmainimage",
		"setmaintitle",
		"special",
		"speciale",
		"sub",
		"subjectpagename",
		"subjectpagenamee",
		"subjectspace",
		"subjectspacee",
		"subpagename",
		"subpagenamee",
		"switch",
		"tag",
		"talkpagename",
		"talkpagenamee",
		"talkspace",
		"talkspacee",
		"time",
		"timel",
		"titleparts",
		"uc",
		"ucfirst",
		"urldecode",
		"urlencode",
		"var",
		"var_final",
		"vardefine",
		"vardefineecho",
		"varexists",
		"vlink",
	],

	behaviorSwitches: [
		"__NOTOC__",
		"__FORCETOC__",
		"__TOC__",
		"__NOEDITSECTION__",
		"__NEWSECTIONLINK__",
		"__NONEWSECTIONLINK__",
		"__NOGALLERY__",
		"__HIDDENCAT__",
		"__EXPECTUNUSEDCATEGORY__",
		"__NOCONTENTCONVERT__",
		"__NOCC__",
		"__NOTITLECONVERT__",
		"__NOTC__",
		"__START__",
		"__END__",
		"__INDEX__",
		"__NOINDEX__",
		"__STATICREDIRECT__",
		"__DISAMBIG__",
	],
};
